import { BarChart3, BadgeCheck, ShieldCheck } from 'lucide-react'
import { getHomeData } from '@/lib/home-data'
import { getPageContent, pageValue } from '@/lib/site-content'
import { PageHero } from '@/components/public/PageHero'
import { PlatformLogo } from '@/components/public/PlatformLogo'
import { PublicPageShell } from '@/components/public/PublicPageShell'
import { compactMoney, money, relativeDate } from '@/components/public/public-format'
import { resolvePublicLanguage } from '@/lib/public-language'

export const revalidate = 60

export default async function PayoutsPage({ searchParams }: { searchParams: Promise<{ lang?: string | string[] }> }) {
  const language = resolvePublicLanguage((await searchParams).lang)
  const [data, content] = await Promise.all([getHomeData(), getPageContent('payouts', language)])
  return <PublicPageShell payouts={data.latestPayouts}><PageHero content={content} fallbackTitle="Pagos verificados, en un solo lugar." fallbackSubtitle="Explora actividad, rankings y evidencia de pagos rastreables." primaryHref="#ultimos" secondaryHref="#metodologia" />
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Total pagado', compactMoney.format(data.stats.totalPaid)], ['Payouts rastreados', data.stats.totalPayouts.toLocaleString('es-CO')], ['Promedio', money.format(data.stats.averagePayout)], ['Mayor payout', money.format(data.stats.largestPayout)]].map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-[#111c2e] p-5"><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block font-mono text-2xl">{value}</strong></div>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-6 px-4 pb-20 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div className="rounded-2xl border border-white/10 bg-[#111c2e] p-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">Ranking por monto</h2><BarChart3 className="size-5 text-cyan-300" /></div>{data.topFirms.map((item, index) => <div key={item.platform.id} className="flex items-center gap-3 border-t border-white/8 py-4"><span className="font-mono text-xs text-slate-600">0{index + 1}</span><PlatformLogo platform={item.platform} small /><div className="min-w-0 flex-1"><p className="truncate font-semibold">{item.platform.name}</p><p className="text-xs text-slate-500">{item.count} payouts</p></div><strong className="font-mono text-emerald-400">{compactMoney.format(item.total)}</strong></div>)}</div><div id="ultimos" className="rounded-2xl border border-white/10 bg-[#111c2e] p-5"><h2 className="mb-3 font-bold">Últimos payouts</h2>{data.latestPayouts.map((payout) => <a key={payout.id} href={payout.sourceUrl || '#'} target={payout.sourceUrl ? '_blank' : undefined} rel="noreferrer" className="grid grid-cols-[1fr_auto] gap-3 border-t border-white/8 py-4"><div className="flex min-w-0 items-center gap-3">{payout.platform && <PlatformLogo platform={payout.platform} small />}<div className="min-w-0"><p className="truncate font-semibold">{payout.platform?.name ?? 'Payout verificado'}</p><p className="text-xs text-slate-500">{relativeDate(payout.payoutDate)} · {payout.verification ?? 'verificado'}</p></div></div><strong className="font-mono text-emerald-400">{money.format(payout.amount)}</strong></a>)}</div></section>
    <section id="metodologia" className="border-t border-white/8 bg-[#0c1626] py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-cyan-300">{pageValue(content, 'methodology', 'badge', 'Verificación')}</p><h2 className="mt-3 text-3xl font-bold">{pageValue(content, 'methodology', 'title', 'Cómo verificamos los payouts')}</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[[ShieldCheck, 'On-chain'], [BadgeCheck, 'Fuente atribuida'], [BarChart3, 'Agregación por firma']].map(([Icon, label]) => <div key={String(label)} className="rounded-2xl border border-white/10 bg-[#111c2e] p-6"><Icon className="size-7 text-cyan-300" /><h3 className="mt-4 font-bold">{String(label)}</h3></div>)}</div></div></section>
  </PublicPageShell>
}
