'use client'
/* eslint-disable @next/next/no-img-element */

import Link from 'next/link'
import { ArrowUpRight, MessageCircle } from 'lucide-react'
import { useMemo,useState } from 'react'
import { SearchInput } from '@/components/shared/SearchInput'
import type { BlogPost,Community } from '@/lib/discovery'

export function CommunitiesCatalog({items}:{items:Community[]}){const[q,setQ]=useState(''),[type,setType]=useState('all');const types=[...new Set(items.map(x=>x.communityType))],query=q.trim().toLowerCase();const shown=items.filter(x=>type==='all'||x.communityType===type).filter(x=>[x.name,x.shortDescription,x.category].some(v=>v?.toLowerCase().includes(query)));const featured=items.filter(x=>x.isFeatured).slice(0,4);return <><Featured title="Comunidades destacadas" items={featured}/><div className="mt-8 flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#111c2e] p-3 lg:flex-row"><SearchInput value={q} onChange={setQ} placeholder="Buscar comunidades..." theme="dark" className="flex-1"/><div className="flex flex-wrap gap-2">{['all',...types].map(v=><button type="button" key={v} onClick={()=>setType(v)} className={chip(type===v)}>{v==='all'?'Todas':labelType(v)}</button>)}</div></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{shown.map(x=><CommunityCard key={x.id} item={x}/>)}</div>{!shown.length&&<Empty text={items.length?'No encontramos comunidades con estos filtros.':'Todavía no hay comunidades publicadas.'}/>}</>}
function Featured({title,items}:{title:string;items:Community[]}){return items.length?<section><p className="tg-eyebrow">Selección editorial</p><h2 className="mt-2 text-2xl font-bold">{title}</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{items.map(x=><CommunityCard key={x.id} item={x}/>)}</div></section>:null}
function CommunityCard({item}:{item:Community}){return <article className="flex min-h-72 flex-col rounded-2xl border border-white/10 bg-[#111c2e] p-5 transition hover:border-amber-300/30"><div className="flex items-start justify-between gap-3">{item.logoUrl?<img src={item.logoUrl} alt={item.logoAlt||item.name} className="size-14 rounded-xl bg-white object-contain p-1"/>:<span className="flex size-14 items-center justify-center rounded-xl bg-white/5 text-amber-300"><MessageCircle/></span>}{item.badge&&<span className="rounded-full border border-amber-300/20 px-2 py-1 text-[10px] uppercase text-amber-200">{item.badge}</span>}</div><h3 className="mt-4 text-xl font-bold">{item.name}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-400">{item.shortDescription||'Comunidad para traders.'}</p><div className="mt-4 flex flex-wrap gap-2">{[labelType(item.communityType),item.languageCode?.toUpperCase(),item.category,item.regionLabel].filter(Boolean).map(v=><span key={v} className="rounded-md bg-white/5 px-2 py-1 text-xs text-slate-300">{v}</span>)}</div><a href={item.joinUrl} target="_blank" rel="noopener noreferrer" className="tg-button-gold mt-auto pt-3">Unirme <ArrowUpRight className="size-4"/></a></article>}

export function BlogCatalog({posts}:{posts:BlogPost[]}){const[q,setQ]=useState(''),[category,setCategory]=useState('Todos');const cats=[...new Set(posts.map(x=>x.category).filter((x):x is string=>Boolean(x)))];const featured=posts.find(x=>x.isFeatured);const shown=useMemo(()=>posts.filter(x=>category==='Todos'||x.category===category).filter(x=>[x.title,x.excerpt,x.category,...x.tags].some(v=>v?.toLowerCase().includes(q.trim().toLowerCase()))),[posts,q,category]);return <>{featured&&<Link href={`/blog/${featured.slug}`} className="grid overflow-hidden rounded-3xl border border-amber-300/20 bg-[#111c2e] md:grid-cols-[1.1fr_.9fr]">{featured.coverUrl?<img src={featured.coverUrl} alt={featured.coverAlt||featured.title} className="h-full min-h-64 w-full object-cover"/>:<div className="tradagora-pattern tradagora-pattern-gold min-h-64"/>}<div className="flex flex-col justify-center p-6 sm:p-8"><p className="tg-eyebrow">{featured.category||'Destacado'}</p><h2 className="mt-3 text-3xl font-bold">{featured.title}</h2><p className="mt-3 leading-7 text-slate-400">{featured.excerpt}</p><span className="mt-5 inline-flex items-center gap-2 font-semibold text-amber-300">Leer artículo <ArrowUpRight className="size-4"/></span></div></Link>}<div className="mt-8 flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#111c2e] p-3 lg:flex-row"><SearchInput value={q} onChange={setQ} placeholder="Buscar artículos..." theme="dark" className="flex-1"/><div className="flex flex-wrap gap-2">{['Todos',...cats].map(v=><button type="button" key={v} onClick={()=>setCategory(v)} className={chip(category===v)}>{v}</button>)}</div></div><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{shown.map(p=><Link href={`/blog/${p.slug}`} key={p.id} className="overflow-hidden rounded-2xl border border-white/10 bg-[#111c2e] transition hover:border-amber-300/30">{p.coverUrl?<img src={p.coverUrl} alt={p.coverAlt||p.title} className="h-44 w-full object-cover"/>:<div className="tradagora-pattern h-44"/>}<div className="p-5"><p className="text-xs uppercase tracking-wider text-amber-300">{p.category||'Artículo'}</p><h3 className="mt-2 text-xl font-bold">{p.title}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-400">{p.excerpt}</p><p className="mt-4 text-xs text-slate-500">{date(p.publishedAt)}{p.authorName?` · ${p.authorName}`:''}</p></div></Link>)}</div>{!shown.length&&<Empty text={posts.length?'No encontramos artículos con estos filtros.':'Todavía no hay artículos publicados.'}/>}</>}
function chip(active:boolean){return`rounded-lg border px-3.5 py-2.5 text-sm font-semibold transition ${active?'border-amber-200/55 bg-[linear-gradient(110deg,#a97313,#e8bb49_55%,#f8d779)] text-slate-950':'border-white/10 bg-white/5 text-slate-300'}`}
function Empty({text}:{text:string}){return <div className="tg-empty mt-5 rounded-2xl p-10 text-center text-slate-400">{text}</div>}
function labelType(v:string){return({discord:'Discord',telegram:'Telegram',whatsapp:'WhatsApp',x:'X',reddit:'Reddit',forum:'Foro',other:'Otra'} as Record<string,string>)[v]??v}
function date(v:string|null){return v?new Intl.DateTimeFormat('es-CO',{dateStyle:'medium'}).format(new Date(v)):'Sin fecha'}
