import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, CalendarClock, WalletCards } from 'lucide-react'
import { PeriodTabs, TrendChart, formatDate, money } from './PayoutTrackerUI'
import { payoutPeriodLabel, type PayoutPeriodKey } from '@/lib/payout-periods'
import type { AwaitedPayoutDetail } from '@/lib/payout-tracker'

export function FirmPayoutDashboard({ detail, period, basePath, language, embedded = false }: { detail: AwaitedPayoutDetail; period: PayoutPeriodKey; basePath: string; language: string; embedded?: boolean }) {
  const { summary, payouts, trend, context } = detail
  const currentTrend = trendForPeriod(trend, period)
  const comparison = comparePeriods(trend, period)
  const total = summary.displayTotalAmount ?? (summary.verifiedPayoutCount ? summary.verifiedAmount : null)
  const count = summary.knownPayoutCount ?? (summary.verifiedPayoutCount || null)
  const largest = summary.knownLargestPayout ?? summary.verifiedLargestPayout
  const average = summary.knownAveragePayout ?? summary.verifiedAveragePayout
  const hasPayoutContext = context.payoutMethods.length > 0 || context.policies.length > 0
  const showConsolidationNote = currentTrend.length === 0 && payouts.length === 0 && !hasPayoutContext
  return <div className={`w-full ${embedded ? 'mt-6 space-y-5' : 'space-y-5'}`}>
    <div className="flex flex-col gap-3 border-b border-white/8 pb-4 lg:flex-row lg:items-center lg:justify-between"><p className="text-sm text-slate-400">Actividad para <strong className="text-slate-200">{payoutPeriodLabel(period)}</strong></p><PeriodTabs active={period} basePath={basePath} language={language} detail extraParams={embedded ? { view: 'payouts' } : undefined} /></div>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Total pagado" value={total === null ? 'Sin total externo disponible' : money(total)} accent={total !== null} primary /><Metric label="Payouts" value={count === null ? '—' : count.toLocaleString('es-CO')} /><Metric label="Mayor payout" value={largest === null ? '—' : money(largest)} /><Metric label="Promedio" value={average === null ? '—' : money(average)} /></div>
    {(currentTrend.length > 0 || comparison) && <div className={`grid gap-5 ${currentTrend.length > 0 && comparison ? 'xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]' : ''}`}>
      {currentTrend.length > 0 && <section className="min-w-0 rounded-2xl border border-white/10 bg-gradient-to-br from-[#132137] to-[#0f192a] p-5 sm:p-7"><h2 className="mb-6 flex items-center gap-2 text-xl font-bold"><BarChart3 className="size-5 text-cyan-300" />Historial de payouts</h2><TrendChart points={currentTrend} /></section>}
      {comparison && <Comparison comparison={comparison} period={period} />}
    </div>}
    {payouts.length > 0 && <section className="rounded-2xl border border-white/10 bg-[#111c2e] p-5 sm:p-7"><h2 className="flex items-center gap-2 text-xl font-bold"><Activity className="size-5 text-emerald-400" />Actividad reciente</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead className="border-b border-white/10 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-3">Monto</th><th className="p-3">Fecha</th><th className="p-3">Método</th><th className="p-3 text-right">Detalle</th></tr></thead><tbody>{payouts.map((payout) => <tr key={payout.id} className="border-b border-white/5 transition hover:bg-white/[.025]"><td className="p-3 font-mono text-emerald-400">{money(Number(payout.amount))}</td><td className="p-3">{formatDate(payout.payout_date)}</td><td className="p-3">{payout.payment_method || '—'}</td><td className="p-3 text-right">{payout.source_url ? <a href={payout.source_url} target="_blank" rel="noreferrer" className="text-cyan-300">Ver registro</a> : '—'}</td></tr>)}</tbody></table></div></section>}
    {hasPayoutContext && <PayoutContext methods={context.payoutMethods} policies={context.policies} />}
    {showConsolidationNote && <p className="px-1 text-sm text-slate-500">El historial detallado de esta firma todavía está en consolidación.</p>}
  </div>
}

function Comparison({ comparison, period }: { comparison: { current: number; previous: number; change: number }; period: PayoutPeriodKey }) { const positive = comparison.change >= 0; return <aside className="rounded-2xl border border-white/10 bg-[#111c2e] p-5 sm:p-7"><p className="font-mono text-xs uppercase tracking-[.18em] text-slate-500">Comparación</p><h2 className="mt-2 text-lg font-bold">{payoutPeriodLabel(period)}</h2><dl className="mt-6 space-y-4"><SmallStat label="Periodo actual" value={money(comparison.current)} /><SmallStat label="Periodo anterior" value={money(comparison.previous)} /></dl><div className={`mt-6 inline-flex items-center gap-2 rounded-xl px-3 py-2 font-mono text-lg font-bold ${positive ? 'bg-emerald-400/10 text-emerald-300' : 'bg-rose-400/10 text-rose-300'}`}>{positive ? <ArrowUpRight className="size-5" /> : <ArrowDownRight className="size-5" />}{Math.abs(comparison.change).toFixed(1)}%</div></aside> }
function PayoutContext({ methods, policies }: { methods: string[]; policies: AwaitedPayoutDetail['context']['policies'] }) { return <section className="grid gap-5 lg:grid-cols-2">{methods.length > 0 && <article className="rounded-2xl border border-white/10 bg-[#111c2e]/80 p-5 sm:p-6"><h2 className="flex items-center gap-2 font-bold"><WalletCards className="size-5 text-[#f7c64b]" />Métodos de retiro</h2><div className="mt-4 flex flex-wrap gap-2">{methods.map((method) => <span key={method} className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-sm text-slate-200">{method}</span>)}</div></article>}{policies.length > 0 && <article className="rounded-2xl border border-white/10 bg-[#111c2e]/80 p-5 sm:p-6"><h2 className="flex items-center gap-2 font-bold"><CalendarClock className="size-5 text-cyan-300" />Ciclos de retiro</h2><div className="mt-4 divide-y divide-white/8">{policies.slice(0, 6).map((policy, index) => <div key={`${policy.challenge}-${policy.option}-${index}`} className="flex items-start justify-between gap-4 py-3 first:pt-0 last:pb-0"><div><p className="text-sm font-semibold">{policy.challenge}</p>{policy.option && <p className="mt-0.5 text-xs text-slate-500">{policy.option}</p>}</div><p className="max-w-48 text-right text-sm text-slate-300">{policy.frequency || (policy.minimumDays !== null ? `Desde ${policy.minimumDays} días` : '—')}</p></div>)}</div></article>}</section> }
function Metric({ label, value, accent = false, primary = false }: { label: string; value: string; accent?: boolean; primary?: boolean }) { return <article className={`min-w-0 rounded-2xl border p-4 sm:p-5 xl:min-h-32 ${primary ? 'border-emerald-400/20 bg-[#13253a] shadow-lg shadow-emerald-950/10' : 'border-white/8 bg-[#111c2e]'}`}><p className="text-[11px] uppercase tracking-[.14em] text-slate-500">{label}</p><p className={`mt-4 break-words font-mono font-bold ${primary ? 'text-2xl sm:text-3xl xl:text-4xl' : 'text-xl sm:text-2xl xl:text-3xl'} ${accent ? 'text-emerald-400' : 'text-slate-100'}`}>{value}</p></article> }
function SmallStat({ label, value }: { label: string; value: string }) { return <div className="flex items-end justify-between gap-3 border-b border-white/8 pb-3"><dt className="text-sm text-slate-500">{label}</dt><dd className="font-mono text-lg font-semibold">{value}</dd></div> }
function trendForPeriod(points: AwaitedPayoutDetail['trend'], period: PayoutPeriodKey) { const days = periodDays(period); if (!days) return points; const since = Date.now() - days * 86_400_000; return points.filter((point) => new Date(point.day).getTime() >= since) }
function comparePeriods(points: AwaitedPayoutDetail['trend'], period: PayoutPeriodKey) { const days = periodDays(period); if (!days) return null; const now = Date.now(), currentStart = now - days * 86_400_000, previousStart = now - days * 2 * 86_400_000; const current = points.filter((p) => new Date(p.day).getTime() >= currentStart).reduce((sum, p) => sum + p.amount, 0); const previous = points.filter((p) => { const time = new Date(p.day).getTime(); return time >= previousStart && time < currentStart }).reduce((sum, p) => sum + p.amount, 0); return current > 0 && previous > 0 ? { current, previous, change: ((current - previous) / previous) * 100 } : null }
function periodDays(period: PayoutPeriodKey) { return period === '7d' ? 7 : period === '30d' ? 30 : period === '365d' ? 365 : null }
