import Link from 'next/link'
import { ArrowRight, ArrowUpRight, BadgeDollarSign, Database, Globe2, ShieldCheck } from 'lucide-react'
import type { HomeOffer, HomePayout, HomePlatform, HomeRankings, PublicCountry } from '@/lib/home-data'
import type { PageContent } from '@/lib/site-content'
import { pageValue, sectionEnabled } from '@/lib/site-content'
import { getContentPage } from '@/lib/content-schema'
import type { PublicLanguage } from '@/lib/public-language'
import type { RecommendableFirm, RecommendationCriteria } from '@/lib/prop-firm-recommender'
import type { PublicOffer } from '@/lib/public-offers'
import { PlatformLogo } from './PlatformLogo'
import { PropFirmFinder } from './PropFirmFinder'
import { HomePayoutRankings } from './HomePayoutRankings'
import { compactMoney, money } from './public-format'
import { FeaturedOffersStrip } from './offers/FeaturedOffersStrip'
import { OfferActivityToast } from './offers/OfferActivityToast'

type Props = {
  content: PageContent
  latestPayouts: HomePayout[]
  featuredPlatforms: HomePlatform[]
  offers: HomeOffer[]
  publicOffers: PublicOffer[]
  language: PublicLanguage
  recommendationFirms: RecommendableFirm[]
  countries: PublicCountry[]
  initialCriteria: Partial<RecommendationCriteria>
  rankings: HomeRankings
  stats: { totalPaid: number | null; totalPayouts: number | null; paidToday: number | null; payoutsToday: number | null; firmsActiveToday: number | null; firmsTracked: number | null; recentUpdatedAt: string | null }
}

export function HomePublic(props: Props) {
  const { content, latestPayouts, featuredPlatforms, publicOffers, language, recommendationFirms, countries, initialCriteria, rankings, stats } = props
  const featuredOffers = publicOffers.filter((offer) => offer.isFeatured)
  const sectionNodes: Record<string, React.ReactNode> = {
    hero: <section className="home-grid"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div><Badge>{pageValue(content, 'hero', 'badge', 'Datos para operar con criterio')}</Badge><h1 className="mt-6 text-5xl font-bold leading-[.98] tracking-[-.055em] sm:text-6xl">{pageValue(content, 'hero', 'title', 'Compara antes de poner tu capital en juego.')}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">{pageValue(content, 'hero', 'subtitle', 'Prop firms, ofertas y pagos verificados en un mismo lugar.')}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row sm:items-center"><Link href={`/prop-firms?lang=${language}`} className="button-gold min-h-12 px-6 py-3.5 text-base">{pageValue(content, 'hero', 'primary_cta', 'Explorar Prop Firms')} <ArrowRight className="size-4" /></Link><Link href={`/payouts?lang=${language}`} className="button-outline min-h-12 px-6 py-3.5 text-base shadow-[inset_0_1px_rgba(255,255,255,.04),0_10px_30px_rgba(0,0,0,.16)]">{pageValue(content, 'hero', 'secondary_cta', 'Ver pagos verificados')} <ArrowUpRight className="size-4" /></Link></div></div><div className="rounded-[1.75rem] border border-white/12 bg-[#111c2e]/90 p-7"><p className="font-mono text-xs uppercase text-slate-400">Actividad verificada hoy</p>{stats.paidToday === null ? <div className="mt-5"><strong className="block text-xl text-white">Sin datos recientes disponibles</strong><p className="mt-2 text-xs text-slate-500">Esto no significa que el monto pagado sea cero.</p></div> : <><strong className="mt-5 block font-mono text-4xl text-emerald-400">{money.format(stats.paidToday)}</strong><p className="mt-2 text-xs text-slate-500">{stats.payoutsToday} retiros · {stats.firmsActiveToday} firmas con actividad</p></>}{stats.recentUpdatedAt && <p className="mt-2 text-[11px] text-slate-600">Última evidencia: {new Date(stats.recentUpdatedAt).toLocaleString('es-CO')}</p>}{latestPayouts.slice(0, 3).map((payout) => <div key={payout.id} className="mt-3 flex items-center gap-3 rounded-xl bg-white/[.04] p-3">{payout.platform && <PlatformLogo platform={payout.platform} small />}<span className="min-w-0 flex-1 truncate text-sm font-semibold">{payout.platform?.name ?? 'Payout verificado'}</span><span className="font-mono text-emerald-400">{money.format(payout.amount)}</span></div>)}<Link href={`/payouts?lang=${language}`} className="mt-4 inline-flex text-sm font-semibold text-[#f7c64b]">Abrir Payout Tracker →</Link></div></div></section>,
    finder: <PropFirmFinder firms={recommendationFirms} countries={countries} language={language} initial={initialCriteria} badge={pageValue(content, 'finder', 'badge', 'Recomendador')} title={pageValue(content, 'finder', 'title', 'Encuentra la Prop Firm adecuada para ti')} subtitle={pageValue(content, 'finder', 'subtitle', 'Cuéntanos cómo operas y Tradagora compara las firmas por ti.')} cta={pageValue(content, 'finder', 'cta', 'Encontrar mis mejores opciones')} />,
    payouts_preview: <section className="border-y border-white/8 bg-[#0c1626] py-16"><SectionHeader badge={pageValue(content, 'payouts_preview', 'badge', 'Payout tracker')} title={pageValue(content, 'payouts_preview', 'title', 'Pagos reales. Evidencia rastreable.')} subtitle={pageValue(content, 'payouts_preview', 'subtitle', 'Evidencias individuales registradas por Tradagora; las métricas externas permanecen separadas en el tracker.')} href={`/payouts?lang=${language}`} cta={pageValue(content, 'payouts_preview', 'cta', 'Ver Payout Tracker')} /><div className="mx-auto mt-8 grid max-w-7xl gap-4 px-4 sm:grid-cols-3 sm:px-6 lg:px-8"><Stat label="Total registrado" value={stats.totalPaid === null ? 'Sin datos' : compactMoney.format(stats.totalPaid)} /><Stat label="Payouts" value={stats.totalPayouts === null ? 'Sin datos' : stats.totalPayouts.toLocaleString('es-CO')} /><Stat label="Firmas con evidencia" value={stats.firmsTracked === null ? 'Sin datos' : String(stats.firmsTracked)} /></div></section>,
    payout_rankings: <HomePayoutRankings rankings={rankings} />,
    featured_firms: featuredPlatforms.length ? <section className="py-20"><SectionHeader badge={pageValue(content, 'featured_firms', 'badge', 'Selección editorial')} title={pageValue(content, 'featured_firms', 'title', 'Prop Firms destacadas')} href={`/prop-firms?lang=${language}`} cta={pageValue(content, 'featured_firms', 'cta', 'Ver todas las firmas')} /><div className="mx-auto mt-8 grid max-w-7xl gap-4 px-4 md:grid-cols-3 sm:px-6 lg:px-8">{featuredPlatforms.slice(0, 6).map((platform) => <article key={platform.id} className="rounded-2xl border border-white/10 bg-[#111c2e] p-6"><div className="flex items-center gap-3"><PlatformLogo platform={platform} /><div><h3 className="font-bold">{platform.name}</h3>{platform.featuredBadge && <p className="mt-1 text-xs text-[#f7c64b]">{platform.featuredBadge}</p>}</div></div><p className="mt-5 min-h-12 text-sm text-slate-400">{platform.description || 'Consulta sus datos y condiciones.'}</p><div className="mt-5 flex gap-3"><Link href={`/prop-firms/${platform.slug}?lang=${language}`} className="inline-flex items-center gap-2 text-sm font-bold">Ver detalles</Link><Link href={`/go/${platform.slug}`} className="inline-flex items-center gap-2 text-sm font-bold text-[#f7c64b]">{platform.featuredCtaLabel || 'Visitar'} <ArrowUpRight className="size-4" /></Link></div></article>)}</div></section> : null,
    featured_offers: featuredOffers.length ? <FeaturedOffersStrip offers={featuredOffers} language={language} global /> : null,
    methodology: <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><Badge>{pageValue(content, 'methodology', 'badge', 'Metodología')}</Badge><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Cómo verificamos la información.</h2><p className="mt-4 max-w-xl leading-7 text-slate-400">Separamos información estructurada, evidencia rastreable, fuentes públicas y relaciones comerciales para que sepas qué estás comparando.</p><Link href={`/comparador?lang=${language}`} className="mt-6 inline-flex items-center gap-2 font-bold text-amber-300">Cómo comparar con criterio <ArrowRight className="size-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2">{[[Database, 'Datos propios', 'Información estructurada que recopilamos y administramos.'], [ShieldCheck, 'Evidencia verificable', 'Payouts y pruebas individuales que pueden rastrearse.'], [Globe2, 'Fuentes públicas', 'Reglas, condiciones y restricciones publicadas por fuentes identificables.'], [BadgeDollarSign, 'Enlaces comerciales', 'La afiliación se identifica y nunca se mezcla con la verificación.']].map(([Icon, title, text]) => <article key={String(title)} className="rounded-2xl border border-white/10 bg-[linear-gradient(145deg,rgba(17,28,46,.96),rgba(8,18,31,.96))] p-5"><div className="flex items-start gap-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl border border-amber-300/15 bg-amber-300/[.06] text-amber-300"><Icon className="size-5" /></span><div><h3 className="font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{String(text)}</p></div></div></article>)}</div></div></section>,
    final_cta: <section className="mx-auto w-full max-w-7xl px-4 pb-20 sm:px-6 lg:px-8"><div className="tradagora-pattern tradagora-pattern-gold overflow-hidden rounded-[2rem] border border-amber-300/20 bg-[linear-gradient(120deg,#101d30,#0a1422)] p-7 sm:p-10"><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="tg-eyebrow">{pageValue(content, 'final_cta', 'badge', 'Decide con contexto')}</p><h2 className="mt-4 max-w-2xl text-3xl font-bold sm:text-4xl">{pageValue(content, 'final_cta', 'title', 'Menos promesas. Más contexto para decidir.')}</h2><p className="mt-4 max-w-xl leading-7 text-slate-400">Compara firmas, evidencia de payouts y ofertas activas sin mezclar fuentes ni intereses comerciales.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href={`/prop-firms?lang=${language}`} className="button-gold px-6 py-3.5">{pageValue(content, 'final_cta', 'cta', 'Explorar firmas')} <ArrowRight className="size-4" /></Link><Link href={`/comparador?lang=${language}`} className="button-outline px-6 py-3.5">Ver metodología</Link></div></div><ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{['Prop Firms comparables', 'Payouts con fuente identificada', 'Ofertas activas y comparador'].map((item) => <li key={item} className="flex items-center gap-3 rounded-xl border border-white/8 bg-white/[.035] px-4 py-3 text-sm font-semibold text-slate-200"><ShieldCheck className="size-4 shrink-0 text-amber-300" />{item}</li>)}</ul></div></div></section>,
  }

  const schema = getContentPage('home')
  const sections = (schema?.sections ?? [])
    .filter((section) => sectionEnabled(content, section.name) && sectionNodes[section.name])
    .sort((a, b) => Number(content[a.name]?.order ?? schema!.sections.indexOf(a) + 1) - Number(content[b.name]?.order ?? schema!.sections.indexOf(b) + 1))

  return <>{sections.map((section) => <div key={section.name} data-home-section={section.name}>{sectionNodes[section.name]}</div>)}{publicOffers.length ? <OfferActivityToast offers={publicOffers} /> : null}</>
}

export function HomeHeroFallback({ content, language }: { content: PageContent; language: PublicLanguage }) {
  return <section className="home-grid"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div><Badge>{pageValue(content, 'hero', 'badge', 'Datos para operar con criterio')}</Badge><h1 className="mt-6 text-5xl font-bold leading-[.98] tracking-[-.055em] sm:text-6xl">{pageValue(content, 'hero', 'title', 'Compara antes de poner tu capital en juego.')}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">{pageValue(content, 'hero', 'subtitle', 'Prop firms, ofertas y pagos verificados en un mismo lugar.')}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={`/prop-firms?lang=${language}`} className="button-gold min-h-12 px-6 py-3.5">{pageValue(content, 'hero', 'primary_cta', 'Explorar Prop Firms')} <ArrowRight className="size-4" /></Link><Link href={`/payouts?lang=${language}`} className="button-outline min-h-12 px-6 py-3.5">{pageValue(content, 'hero', 'secondary_cta', 'Ver pagos verificados')} <ArrowUpRight className="size-4" /></Link></div></div><div aria-hidden="true" className="min-h-64 animate-pulse rounded-[1.75rem] border border-white/8 bg-[#111c2e]/55" /></div></section>
}

function Badge({ children }: { children: React.ReactNode }) { return <span className="inline-flex rounded-full border border-cyan-300/25 bg-cyan-300/[.07] px-3 py-2 font-mono text-[11px] uppercase tracking-[.18em] text-cyan-300">{children}</span> }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-[#111c2e] p-5"><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block font-mono text-2xl">{value}</strong></div> }
function SectionHeader({ badge, title, subtitle, href, cta }: { badge: string; title: string; subtitle?: string; href: string; cta: string }) { return <div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-4 sm:flex-row sm:items-end sm:px-6 lg:px-8"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-cyan-300">{badge}</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">{title}</h2>{subtitle && <p className="mt-3 text-slate-400">{subtitle}</p>}</div><Link href={href} className="inline-flex items-center gap-2 font-bold text-[#f7c64b]">{cta} <ArrowRight className="size-4" /></Link></div> }
