'use client'
import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowUpRight, Search } from 'lucide-react'
import type { DirectoryFirm } from '@/lib/prop-firm-directory'

type Filter = 'all' | 'new' | 'cfd' | 'futures'
export function PropFirmDirectory({ firms, language }: { firms: DirectoryFirm[]; language: string }) {
  const [search, setSearch] = useState(''), [filter, setFilter] = useState<Filter>('all'), [order, setOrder] = useState<'popular' | 'name'>('popular')
  const visible = useMemo(() => firms.filter((firm) => firm.name.toLocaleLowerCase('es').includes(search.trim().toLocaleLowerCase('es'))).filter((firm) => filter === 'all' || filter === 'new' ? filter === 'all' || firm.isNew : firm.markets.includes(filter)).sort((a, b) => order === 'name' ? a.name.localeCompare(b.name, 'es') : b.popularity - a.popularity || a.name.localeCompare(b.name, 'es')), [firms, search, filter, order])
  return <div>
    <div className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#111c2e] p-3 lg:flex-row lg:items-center"><label className="flex min-w-0 flex-1 items-center gap-3 rounded-xl border border-white/10 bg-black/15 px-4"><Search className="size-4 shrink-0 text-slate-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar Prop Firm" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none placeholder:text-slate-600" /></label><div className="flex flex-wrap gap-2">{([['all', 'Todas'], ['new', 'Nuevas'], ['cfd', 'CFD'], ['futures', 'Futures']] as const).map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg px-3.5 py-2.5 text-sm font-semibold transition ${filter === value ? 'bg-[#f7c64b] text-slate-950' : 'bg-white/5 text-slate-300 hover:bg-white/10'}`}>{label}</button>)}</div><select value={order} onChange={(event) => setOrder(event.target.value as 'popular' | 'name')} className="rounded-xl border border-white/10 bg-[#0d1728] px-4 py-3 text-sm"><option value="popular">Popularidad</option><option value="name">Nombre</option></select></div>
    {filter === 'new' && <p className="mt-4 rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-4 text-sm text-cyan-100">Las firmas nuevas pueden tener un historial limitado. Revisa sus condiciones, regulación y experiencia de usuarios antes de operar.</p>}
    <div className="mt-5 hidden lg:block"><div className="grid grid-cols-[minmax(240px,1.4fr)_minmax(140px,.7fr)_130px_minmax(190px,1fr)_130px_120px] gap-4 px-5 pb-3 text-[11px] font-semibold uppercase tracking-[.14em] text-slate-500"><span>Firma</span><span>País</span><span>Operación</span><span>Mercados / activos</span><span>Profit split</span><span className="text-right">Acción</span></div><div className="space-y-2">{visible.map((firm) => <DesktopRow key={firm.id} firm={firm} language={language} />)}</div></div>
    <div className="mt-5 space-y-3 lg:hidden">{visible.map((firm) => <MobileCard key={firm.id} firm={firm} language={language} />)}</div>
    {!visible.length && <p className="mt-5 rounded-2xl border border-white/10 bg-[#111c2e] p-10 text-center text-slate-400">No encontramos firmas con estos filtros.</p>}
  </div>
}
function DesktopRow({ firm, language }: { firm: DirectoryFirm; language: string }) { return <article className="group relative grid min-h-20 cursor-pointer grid-cols-[minmax(240px,1.4fr)_minmax(140px,.7fr)_130px_minmax(190px,1fr)_130px_120px] items-center gap-4 rounded-xl border border-white/8 bg-[#111c2e]/75 px-5 py-3 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-cyan-300/25 hover:bg-[#152238] hover:shadow-lg hover:shadow-black/10 focus-within:ring-2 focus-within:ring-cyan-300/40"><FullRowLink firm={firm} language={language} /><FirmIdentity firm={firm} /><MissingValue value={firm.country} /><MissingValue value={operatingYears(firm.foundedAt, false)} /><MarketBadges markets={firm.markets} /><MissingValue value={firm.profitSplit === null ? null : `Hasta ${firm.profitSplit}%`} mono /><AffiliateAction firm={firm} /></article> }
function MobileCard({ firm, language }: { firm: DirectoryFirm; language: string }) { return <article className="relative cursor-pointer rounded-2xl border border-white/10 bg-[#111c2e] p-4 shadow-sm transition active:bg-[#152238] focus-within:ring-2 focus-within:ring-cyan-300/40"><FullRowLink firm={firm} language={language} /><FirmIdentity firm={firm} /><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Fact label="País" value={firm.country} /><Fact label="Operación" value={operatingYears(firm.foundedAt, false)} /><div className="col-span-2"><p className="text-[10px] uppercase tracking-wider text-slate-500">Mercados</p><div className="mt-2"><MarketBadges markets={firm.markets} /></div></div>{firm.profitSplit !== null && <Fact label="Profit split" value={`Hasta ${firm.profitSplit}%`} />}</div><div className="relative z-10 mt-4"><AffiliateAction firm={firm} /></div></article> }
function FirmIdentity({ firm }: { firm: DirectoryFirm }) { return <div className="flex min-w-0 items-center gap-3">{firm.logoUrl ? <FirmLogo firm={firm} /> : <span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-white/5 font-bold">{firm.name.slice(0, 2)}</span>}<div className="min-w-0"><div className="flex items-center gap-2"><h2 className="truncate font-bold">{firm.name}</h2>{firm.isNew && <span className="shrink-0 rounded-full bg-cyan-300/10 px-2 py-1 text-[10px] font-bold uppercase text-cyan-300">Nueva</span>}</div></div></div> }
function MarketBadges({ markets }: { markets: string[] }) { return markets.length ? <div className="flex flex-wrap gap-1.5">{markets.map((market) => <span key={market} className="rounded-md border border-white/8 bg-white/5 px-2 py-1 text-xs text-slate-300">{marketLabel(market)}</span>)}</div> : <span className="text-slate-600">—</span> }
function FullRowLink({ firm, language }: { firm: DirectoryFirm; language: string }) { return <Link href={`/prop-firms/${firm.slug}?lang=${language}`} aria-label={`Ver ${firm.name}`} className="absolute inset-0 z-[5] rounded-xl" /> }
function AffiliateAction({ firm }: { firm: DirectoryFirm }) { return <Link href={`/go/${firm.slug}`} className="relative z-10 inline-flex w-full items-center justify-center gap-1 rounded-lg bg-[#f7c64b] px-3 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-[#ffd66c]">Visitar <ArrowUpRight className="size-4" /></Link> }
function MissingValue({ value, mono = false }: { value: string | null; mono?: boolean }) { return value ? <span className={`${mono ? 'font-mono font-semibold' : ''} text-sm text-slate-300`}>{value}</span> : <span aria-label="Información pendiente" className="h-px w-5 bg-white/10" /> }
function Fact({ label, value }: { label: string; value: string | null }) { return <div><p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-slate-300">{value || '—'}</p></div> }
function operatingYears(value: string | null, verbose = true) { if (!value) return null; const founded = new Date(`${value}T00:00:00Z`), now = new Date(); let years = now.getUTCFullYear() - founded.getUTCFullYear(); if (now.getUTCMonth() < founded.getUTCMonth() || (now.getUTCMonth() === founded.getUTCMonth() && now.getUTCDate() < founded.getUTCDate())) years--; return `${Math.max(0, years)} ${years === 1 ? 'año' : 'años'}${verbose ? ' operando' : ''}` }
function marketLabel(value: string) { return ({ cfd: 'CFD', futures: 'Futures', crypto: 'Crypto', options: 'Opciones' } as Record<string, string>)[value] ?? value }
function FirmLogo({ firm }: { firm: DirectoryFirm }) {
  // Las imágenes son administradas por Supabase y pueden usar hosts dinámicos.
  // eslint-disable-next-line @next/next/no-img-element
  return <img src={firm.logoUrl ?? ''} alt={firm.logoAlt || firm.name} className="size-11 shrink-0 rounded-xl border border-white/10 bg-white object-contain p-1" />
}
