import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { AdminFirmIdentity, StatusBadge } from '@/components/admin/AdminDirectory'
import { createClient } from '@/lib/supabase/server'

export default async function PlatformPayoutsPage({ params, searchParams }: { params: Promise<{ platformId: string }>; searchParams: Promise<{ returnTo?: string }> }) {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect('/login')
  const [{ platformId }, query] = await Promise.all([params, searchParams])
  const [firm, payouts, sources, mappings, metrics] = await Promise.all([
    supabase.from('platforms').select('id, name, logo_url, media:logo_media_id(file_url, alt_text)').eq('id', platformId).eq('type', 'prop_firm').maybeSingle(),
    supabase.from('payouts').select('id, amount, currency, payout_date, payment_method, verification_status, source_url, external_id').eq('platform_id', platformId).order('payout_date', { ascending: false }).limit(25),
    supabase.from('payout_sources').select('id, name, source_type, status, last_sync_at, last_error').eq('platform_id', platformId).order('name'),
    supabase.from('external_platform_mappings').select('id, provider, external_name, external_market, active').eq('platform_id', platformId).order('provider'),
    supabase.from('platform_payout_metrics').select('id, period_key, source_name, verification_level, amount, payout_count, updated_at').eq('platform_id', platformId).eq('is_current', true).order('updated_at', { ascending: false }),
  ])
  if (firm.error || payouts.error || sources.error || mappings.error || metrics.error) throw new Error(firm.error?.message ?? payouts.error?.message ?? sources.error?.message ?? mappings.error?.message ?? metrics.error?.message)
  if (!firm.data) notFound()
  const back = safeReturn(query.returnTo, '/admin/payouts')
  return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl"><Link href={back} className="text-sm text-slate-600 hover:text-black">← Volver al directorio</Link><header className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><AdminFirmIdentity name={firm.data.name} media={firm.data.media} legacyUrl={firm.data.logo_url} /><Link href={`/admin/platforms/${platformId}/edit`} className="rounded-lg border bg-white px-4 py-2.5 text-sm font-medium">Editar Prop Firm</Link></header>
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><Summary label="Pagos verificados" value={String(payouts.data?.length ?? 0)} note="Últimos 25 mostrados" /><Summary label="Fuentes" value={String(sources.data?.length ?? 0)} /><Summary label="Métricas actuales" value={String(metrics.data?.length ?? 0)} /></div>
    <Section title="Resumen automático"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="text-left text-slate-500"><tr><th className="py-3">Periodo</th><th>Fuente</th><th>Verificación</th><th>Monto</th><th>Payouts</th><th>Actualizado</th></tr></thead><tbody>{metrics.data?.map((item) => <tr key={item.id} className="border-t"><td className="py-3">{item.period_key}</td><td>{item.source_name || '—'}</td><td>{item.verification_level}</td><td>{item.amount === null ? '—' : Number(item.amount).toLocaleString('en-US', { style: 'currency', currency: 'USD' })}</td><td>{item.payout_count ?? '—'}</td><td>{new Date(item.updated_at).toLocaleDateString('es-CO')}</td></tr>)}{!metrics.data?.length && <tr><td colSpan={6} className="py-8 text-center text-slate-500">Sin métricas automáticas.</td></tr>}</tbody></table></div></Section>
    <Section title="Fuentes y mappings" action={<Link href="/admin/payouts/sources/new" className="rounded-lg bg-black px-3 py-2 text-sm text-white">+ Nueva fuente</Link>}><div className="grid gap-3 md:grid-cols-2">{sources.data?.map((source) => <article key={source.id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{source.name}</p><p className="mt-1 text-xs text-slate-500">{source.source_type} · {source.last_sync_at ? new Date(source.last_sync_at).toLocaleString('es-CO') : 'Sin sincronizar'}</p></div><StatusBadge tone={source.status ? 'success' : 'neutral'}>{source.status ? 'Activa' : 'Inactiva'}</StatusBadge></div>{source.last_error && <p className="mt-3 text-xs text-red-600">{source.last_error}</p>}<Link href={`/admin/payouts/sources/${source.id}/edit`} className="mt-3 inline-flex text-sm font-medium underline">Editar fuente</Link></article>)}{mappings.data?.map((mapping) => <article key={mapping.id} className="rounded-lg border p-4"><p className="font-medium">Mapping · {mapping.provider}</p><p className="mt-1 text-sm text-slate-600">{mapping.external_name} · {mapping.external_market}</p><StatusBadge tone={mapping.active ? 'success' : 'neutral'}>{mapping.active ? 'Activo' : 'Inactivo'}</StatusBadge></article>)}{!sources.data?.length && !mappings.data?.length && <p className="text-sm text-slate-500">Sin fuentes ni mappings configurados.</p>}</div></Section>
    <Section title="Pagos verificados recientes"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="text-left text-slate-500"><tr><th className="py-3">Fecha</th><th>Monto</th><th>Método</th><th>Verificación</th><th>Transacción</th></tr></thead><tbody>{payouts.data?.map((item) => <tr key={item.id} className="border-t"><td className="py-3">{new Date(item.payout_date).toLocaleString('es-CO')}</td><td>{Number(item.amount).toLocaleString('en-US', { style: 'currency', currency: item.currency || 'USD' })}</td><td>{item.payment_method || '—'}</td><td>{item.verification_status || '—'}</td><td>{item.source_url ? <a href={item.source_url} target="_blank" rel="noreferrer" className="font-mono text-xs underline">{item.external_id?.slice(0, 12)}…</a> : '—'}</td></tr>)}{!payouts.data?.length && <tr><td colSpan={5} className="py-8 text-center text-slate-500">No hay payouts verificados.</td></tr>}</tbody></table></div></Section>
  </div></main>
}

function Summary({ label, value, note }: { label: string; value: string; note?: string }) { return <div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p>{note && <p className="mt-1 text-xs text-slate-400">{note}</p>}</div> }
function Section({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="mt-6 rounded-xl border bg-white p-5"><header className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{title}</h2>{action}</header>{children}</section> }
function safeReturn(value: string | undefined, fallback: string) { return value?.startsWith('/admin/') ? value : fallback }
