export type EditorValues = Record<string, Record<string, string>>
export type TranslationEntry = { key: string; translatedValue: string }
export type SaveCandidate = { key: string; language: string; value: string; type: string }

export function applyTranslationBatch(
  values: EditorValues,
  dirtyFields: ReadonlySet<string>,
  autoGenerated: ReadonlySet<string>,
  translations: TranslationEntry[],
  targetLanguage: string
) {
  const nextValues = structuredClone(values)
  const nextDirtyFields = new Set(dirtyFields)
  const nextAutoGenerated = new Set(autoGenerated)
  const translatedKeys: string[] = []

  for (const translation of translations) {
    if (!nextValues[translation.key]) continue
    const identity = contentIdentity(translation.key, targetLanguage)
    nextValues[translation.key][targetLanguage] = translation.translatedValue
    nextDirtyFields.add(identity)
    nextAutoGenerated.add(identity)
    translatedKeys.push(identity)
  }

  return { nextValues, nextDirtyFields, nextAutoGenerated, translatedKeys }
}

export function buildSaveCandidates(
  values: EditorValues,
  dirtyFields: ReadonlySet<string>,
  fieldTypes: ReadonlyMap<string, string>
): SaveCandidate[] {
  return [...dirtyFields].flatMap((identity) => {
    const parsed = parseContentIdentity(identity)
    if (!parsed || !fieldTypes.has(parsed.key)) return []
    return [{
      key: parsed.key,
      language: parsed.language,
      value: values[parsed.key]?.[parsed.language] ?? '',
      type: fieldTypes.get(parsed.key) ?? 'text',
    }]
  })
}

export function contentIdentity(key: string, language: string) {
  return `${key}:${language}`
}

function parseContentIdentity(identity: string) {
  const separator = identity.lastIndexOf(':')
  if (separator < 1 || separator === identity.length - 1) return null
  return { key: identity.slice(0, separator), language: identity.slice(separator + 1) }
}
