import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowUpRight, Database, ShieldCheck } from 'lucide-react'
import { notFound } from 'next/navigation'
import { CoverageBadge, CoverageValue, MetricValue, PeriodTabs, TrackerLogo, TrendChart, formatDate, marketLabel, money, sourceTypeLabel } from '@/components/public/PayoutTrackerUI'
import { PublicPageShell } from '@/components/public/PublicPageShell'
import { payoutPeriod, payoutPeriodLabel } from '@/lib/payout-periods'
import { getLatestPayoutTicker, getPayoutFirmDetail, type PayoutFirmSummary } from '@/lib/payout-tracker'
import { resolvePublicLanguage } from '@/lib/public-language'
import { createClient } from '@/lib/supabase/server'

export const revalidate = 60
type Props = { params: Promise<{ slug: string }>; searchParams: Promise<{ lang?: string | string[]; period?: string | string[] }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const supabase = await createClient()
  const { data } = await supabase.from('platforms').select('name').eq('slug', slug).eq('type', 'prop_firm').maybeSingle()
  return data ? { title: `${data.name} Payouts, Payment History & Verification | Tragadora`, description: `Compara datos externos de referencia con payouts verificados por Tragadora para ${data.name}.` } : {}
}

export default async function PayoutFirmPage({ params, searchParams }: Props) {
  const [{ slug }, query] = await Promise.all([params, searchParams])
  const language = resolvePublicLanguage(query.lang)
  const period = payoutPeriod(scalar(query.period), 'all')
  const [detail, ticker] = await Promise.all([getPayoutFirmDetail(slug, period), getLatestPayoutTicker()])
  if (!detail) notFound()
  const { summary, metrics, sources, payouts, trend } = detail

  return <PublicPageShell payouts={ticker} language={language}>
    <section className="border-b border-white/8 bg-[radial-gradient(circle_at_top_right,rgba(16,185,129,.13),transparent_38%)]"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><Link href={`/payouts?lang=${language}`} className="text-sm text-cyan-300">← Volver al Payout Tracker</Link><div className="mt-8 flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><div className="flex items-center gap-4"><TrackerLogo summary={summary} large /><div><p className="font-mono text-xs uppercase tracking-[.2em] text-cyan-300">Payout intelligence</p><h1 className="mt-1 text-4xl font-bold sm:text-5xl">{summary.name}</h1></div></div><div className="mt-5 flex flex-wrap gap-2">{summary.markets.map((market) => <span key={market} className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs">{marketLabel(market)}</span>)}<CoverageBadge level={summary.displayTotalVerificationLevel} /></div></div>{detail.websiteUrl && <a href={detail.websiteUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-5 py-3 font-semibold">Web oficial <ArrowUpRight className="size-4" /></a>}</div><div className="mt-8"><PeriodTabs active={period} basePath={`/payouts/${slug}`} language={language} /></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="mb-4 text-sm text-slate-400">Comparación para <strong className="text-white">{payoutPeriodLabel(period)}</strong></p><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><CardMetric label="Total conocido" value={summary.displayTotalAmount} empty="Sin datos externos" note={summary.displayTotalAmount === null ? 'Sin total comparable' : `Referencia externa · ${payoutPeriodLabel(period)}`} /><CardMetric label="Verificado por Tragadora" value={summary.verifiedPayoutCount ? summary.verifiedAmount : null} accent note="Registros propios verificables" /><CoverageCard summary={summary} /><CardMetric label="Volumen aún no verificado" value={summary.unverifiedCoverageAmount} note="Diferencia informativa; no implica pagos inválidos" /></div></section>

    <div className="mx-auto grid max-w-7xl gap-8 px-4 pb-24 sm:px-6 lg:px-8">
      <Panel title="Comparación del periodo" icon={<ShieldCheck className="size-5 text-emerald-400" />}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><CompareMetric label="Cantidad de payouts" known={summary.knownPayoutCount} verified={summary.verifiedPayoutCount || null} count /><CompareMetric label="Mayor payout" known={summary.knownLargestPayout} verified={summary.verifiedLargestPayout} /><CompareMetric label="Promedio" known={summary.knownAveragePayout} verified={summary.verifiedAveragePayout} /></div><p className="mt-6 rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-4 text-sm leading-6 text-cyan-100">Los datos externos de referencia provienen actualmente de MondoTraders. Tragadora verifica de forma independiente una parte del volumen mediante sus propias fuentes y nunca suma ambas mediciones.</p><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-3"><SourceStat label="Tiempo de payout externo" value={duration(summary.knownMedianTimeMinutes)} /><SourceStat label="Última actualización externa" value={summary.displayTotalUpdatedAt ? formatDate(summary.displayTotalUpdatedAt) : 'Sin datos externos'} /><SourceStat label="Último payout verificado" value={summary.verifiedLastPayoutAt ? formatDate(summary.verifiedLastPayoutAt) : 'Sin payouts en este periodo'} /></dl></Panel>

      <Panel title="Tendencias verificadas" icon={<Database className="size-5 text-cyan-300" />}><TrendChart points={trend} /></Panel>

      <Panel title="Fuentes de datos"><div className="grid gap-4 lg:grid-cols-2">{sources.map((source) => <article key={source.id} className="rounded-xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-slate-500">{source.source_type}</p><h3 className="mt-1 font-bold">{source.name}</h3></div><span className={`rounded-full px-2 py-1 text-xs ${source.status ? 'bg-emerald-400/10 text-emerald-300' : 'bg-white/5 text-slate-500'}`}>{source.status ? 'Activa' : 'Inactiva'}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><SourceStat label="Verificación" value={String(source.config?.verification ?? 'Sin clasificar')} /><SourceStat label="Payouts relacionados" value={source.payoutCount.toLocaleString('es-CO')} /><SourceStat label="Última sincronización" value={source.last_sync_at ? formatDate(source.last_sync_at) : 'Sin datos'} /><SourceStat label="Último payout" value={source.lastPayoutAt ? formatDate(source.lastPayoutAt) : 'Sin datos'} /></dl>{source.last_error && <p className="mt-4 rounded-lg bg-rose-400/10 p-3 text-xs text-rose-300">{source.last_error}</p>}</article>)}{metrics.map((metric) => <article key={metric.id} className="rounded-xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{sourceTypeLabel(metric.source_type)}</p><h3 className="mt-1 font-bold">{metric.source_name || 'Fuente sin nombre'} · {payoutPeriodLabel(metric.period_key)}</h3><div className="mt-4"><CoverageBadge level={metric.verification_level} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><SourceStat label="Total conocido" value={metric.amount === null ? 'Sin datos' : money(metric.amount)} /><SourceStat label="Actualizado" value={formatDate(metric.updated_at)} /></dl>{metric.source_url && <a href={metric.source_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-sm text-cyan-300">Abrir fuente <ArrowUpRight className="size-3.5" /></a>}</article>)}</div>{!sources.length && !metrics.length && <p className="text-slate-500">Sin fuentes registradas.</p>}</Panel>

      <Panel title="Últimos payouts verificados"><p className="mb-2 text-xs text-slate-500 md:hidden">Desliza horizontalmente para consultar la evidencia y verificación.</p><div className="max-w-full overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b border-white/10 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-3">Fecha</th><th className="p-3">Monto</th><th className="p-3">Fuente</th><th className="p-3">Método</th><th className="p-3">Verificación</th><th className="p-3">Evidencia</th></tr></thead><tbody>{payouts.map((payout) => <tr key={payout.id} className="border-b border-white/5"><td className="p-3">{formatDate(payout.payout_date)}</td><td className="p-3 font-mono text-emerald-400">{money(Number(payout.amount))}</td><td className="p-3">{payout.source}</td><td className="p-3">{payout.payment_method || '—'}</td><td className="p-3">{payout.verification_status}</td><td className="p-3">{payout.source_url ? <a href={payout.source_url} target="_blank" rel="noreferrer" className="text-cyan-300">Ver transacción</a> : '—'}</td></tr>)}</tbody></table>{!payouts.length && <p className="p-8 text-center text-slate-500">Sin payouts individuales disponibles en este periodo.</p>}</div></Panel>
    </div>
  </PublicPageShell>
}

function Panel({ title, icon, children }: { title: string; icon?: React.ReactNode; children: React.ReactNode }) { return <section className="min-w-0 rounded-2xl border border-white/10 bg-[#111c2e] p-5 sm:p-8"><div className="mb-6 flex items-center gap-2">{icon}<h2 className="text-xl font-bold sm:text-2xl">{title}</h2></div>{children}</section> }
function CardMetric({ label, value, note, empty, accent = false }: { label: string; value?: number | null; note?: string; empty?: string; accent?: boolean }) { return <article className="min-w-0 rounded-2xl border border-white/10 bg-[#111c2e] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><div className="mt-3 break-words text-xl sm:text-2xl">{value == null && empty ? <span className="text-sm text-slate-500">{empty}</span> : <MetricValue value={value ?? null} accent={accent} />}</div>{note && <p className="mt-2 break-words text-xs text-slate-500">{note}</p>}</article> }
function CoverageCard({ summary }: { summary: PayoutFirmSummary }) { return <article className="min-w-0 rounded-2xl border border-white/10 bg-[#111c2e] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">Cobertura verificada</p><div className="mt-3 text-xl sm:text-2xl"><CoverageValue summary={summary} /></div></article> }
function CompareMetric({ label, known, verified, count = false }: { label: string; known: number | null; verified: number | null; count?: boolean }) { const render = (value: number | null) => value === null ? 'Sin datos' : count ? value.toLocaleString('es-CO') : money(value); return <article className="rounded-xl bg-white/5 p-4"><p className="font-semibold">{label}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><SourceStat label="Externo conocido" value={render(known)} /><SourceStat label="Tragadora" value={render(verified)} /></dl></article> }
function SourceStat({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words text-slate-200">{value}</dd></div> }
function duration(value: number | null) { if (value === null) return 'Sin datos'; if (value < 60) return `${value} min`; if (value < 1_440) return `${new Intl.NumberFormat('es-CO', { maximumFractionDigits: 1 }).format(value / 60)} h`; return `${new Intl.NumberFormat('es-CO', { maximumFractionDigits: 1 }).format(value / 1_440)} días` }
function scalar(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? '' : value ?? '' }
