'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowDown, ArrowUp, Languages, RefreshCw } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import type { ContentPageSchema } from '@/lib/content-schema'
import { applyTranslationBatch, buildSaveCandidates, contentIdentity } from '@/lib/content-editor-state'

type Language = { code: string; name: string; native_name: string; is_default: boolean }
type Values = Record<string, Record<string, string>>
type Config = Record<string, { enabled: boolean; order: string; align: string; titleSize: string }>
type TranslationMeta = { key: string; language: string; source_updated_at: string | null; translated_at: string | null; translation_method: 'manual' | 'auto_generated'; manually_edited: boolean }
type ProviderStatus = { provider: string; available: boolean; mode: 'checking' | 'available' | 'unavailable' | 'local_only' | 'not_configured'; message: string }

const supabase = createClient()
const CONFIG_FIELDS = new Set(['enabled', 'order', 'align', 'title_size'])

export function PageContentEditor({ page, translationProviderConfigured }: { page: ContentPageSchema; translationProviderConfigured: boolean }) {
  const [languages, setLanguages] = useState<Language[]>([])
  const [selectedLanguage, setSelectedLanguage] = useState('es')
  const [values, setValues] = useState<Values>({})
  const [config, setConfig] = useState<Config>(() => createInitialConfig(page))
  const [metadata, setMetadata] = useState<Record<string, TranslationMeta>>({})
  const [sourceUpdatedAt, setSourceUpdatedAt] = useState<Record<string, string>>({})
  const [autoGenerated, setAutoGenerated] = useState<Set<string>>(new Set())
  const [dirtyFields, setDirtyFields] = useState<Set<string>>(new Set())
  const [overwriteTranslations, setOverwriteTranslations] = useState(false)
  const [providerStatus, setProviderStatus] = useState<ProviderStatus>({ provider: '', available: false, mode: 'checking', message: translationProviderConfigured ? 'Comprobando proveedor de traducción…' : 'Comprobando disponibilidad local…' })
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [translating, setTranslating] = useState(false)
  const [message, setMessage] = useState(''), [error, setError] = useState('')

  useEffect(() => {
    async function load() {
      const [languagesResult, contentResult, metadataResult] = await Promise.all([
        supabase.from('languages').select('code, name, native_name, is_default').eq('is_active', true).order('sort_order').order('name'),
        supabase.from('site_content').select('key, language, value, updated_at').like('key', `${page.slug}.%`),
        supabase.from('content_translation_meta').select('key, language, source_updated_at, translated_at, translation_method, manually_edited').like('key', `${page.slug}.%`),
      ])
      if (languagesResult.error) { setError(languagesResult.error.message); setLoading(false); return }
      const activeLanguages = languagesResult.data ?? []
      if (!activeLanguages.length) { setError('No hay idiomas activos. Ejecuta la migración o activa un idioma.'); setLoading(false); return }
      const baseLanguage = activeLanguages.find((language) => language.is_default) ?? activeLanguages[0]
      const nextValues: Values = {}, nextConfig = createInitialConfig(page), nextSourceDates: Record<string, string> = {}
      page.sections.forEach((section) => {
        for (const field of section.translatableFields) {
          const key = contentKey(page.slug, section.name, field.name)
          nextValues[key] = Object.fromEntries(activeLanguages.map((language) => [language.code, language.code === baseLanguage.code ? field.fallback : '']))
        }
      })
      const rows = contentResult.data ?? []
      for (const row of [...rows.filter((item) => item.language !== 'global'), ...rows.filter((item) => item.language === 'global')]) {
        const [, sectionName, fieldName] = row.key.split('.')
        if (!nextConfig[sectionName]) continue
        if (CONFIG_FIELDS.has(fieldName)) {
          if (row.language !== 'global' && rows.some((item) => item.key === row.key && item.language === 'global')) continue
          applyConfig(nextConfig[sectionName], fieldName, row.value)
        } else if (nextValues[row.key] && activeLanguages.some((language) => language.code === row.language)) {
          nextValues[row.key][row.language] = row.value
          if (row.language === baseLanguage.code && row.updated_at) nextSourceDates[row.key] = row.updated_at
        }
      }
      const nextMetadata = Object.fromEntries((metadataResult.data ?? []).map((item) => [`${item.key}:${item.language}`, item as TranslationMeta]))
      setLanguages(activeLanguages); setSelectedLanguage(baseLanguage.code); setValues(nextValues); setConfig(nextConfig); setMetadata(nextMetadata); setSourceUpdatedAt(nextSourceDates); setDirtyFields(new Set()); setLoading(false)
      const queryError = contentResult.error ?? metadataResult.error
      if (queryError) setError(queryError.message)
    }
    void load()
  }, [page])

  const baseLanguage = languages.find((language) => language.is_default) ?? languages[0]
  const selected = languages.find((language) => language.code === selectedLanguage) ?? baseLanguage
  const orderedSections = loading ? [] : [...page.sections].sort((a, b) => Number(config[a.name]?.order ?? page.sections.indexOf(a) + 1) - Number(config[b.name]?.order ?? page.sections.indexOf(b) + 1))
  const allFieldKeys = page.sections.flatMap((section) => section.translatableFields.map((field) => contentKey(page.slug, section.name, field.name)))
  const fieldTypes = new Map(page.sections.flatMap((section) => section.translatableFields.map((field) => [contentKey(page.slug, section.name, field.name), field.type ?? 'text'] as const)))
  const progress = translationProgress(allFieldKeys, values, selectedLanguage, baseLanguage?.code)

  useEffect(() => {
    if (!baseLanguage || !selected) return
    const controller = new AbortController()
    async function checkProvider() {
      try {
        const response = await fetch(`/api/admin/translations?source=${encodeURIComponent(baseLanguage.code)}&target=${encodeURIComponent(selected.code)}`, { cache: 'no-store', signal: controller.signal })
        const result = await response.json() as Partial<ProviderStatus> & { error?: string }
        if (!response.ok) throw new Error(result.error ?? 'No se pudo comprobar el proveedor.')
        setProviderStatus({ provider: result.provider ?? '', available: Boolean(result.available), mode: result.mode ?? 'unavailable', message: result.message ?? 'Traducción automática no disponible.' })
      } catch (providerError) {
        if (controller.signal.aborted) return
        console.warn('Translation provider status check failed:', providerError instanceof Error ? providerError.name : 'UnknownError')
        setProviderStatus({ provider: 'libretranslate', available: false, mode: 'unavailable', message: 'Traducción automática no disponible. Inicia LibreTranslate para traducir automáticamente.' })
      }
    }
    void checkProvider()
    return () => controller.abort()
  }, [baseLanguage, selected])

  function moveSection(sectionName: string, direction: -1 | 1) {
    const index = orderedSections.findIndex((section) => section.name === sectionName), target = orderedSections[index + direction]
    if (!target) return
    setConfig((current) => ({ ...current, [sectionName]: { ...current[sectionName], order: current[target.name].order }, [target.name]: { ...current[target.name], order: current[sectionName].order } }))
  }

  function updateValue(key: string, language: string, value: string) {
    setValues((current) => ({ ...current, [key]: { ...current[key], [language]: value } }))
    setDirtyFields((current) => new Set(current).add(`${key}:${language}`))
    setAutoGenerated((current) => { const next = new Set(current); next.delete(`${key}:${language}`); return next })
  }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError(''); setMessage('')
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) { setError('Debes iniciar sesión.'); setSaving(false); return }
    const now = new Date().toISOString(), nextSourceDates = { ...sourceUpdatedAt }, nextMetadata = { ...metadata }
    const saveCandidates = buildSaveCandidates(values, dirtyFields, fieldTypes)
    for (const candidate of saveCandidates) if (candidate.language === baseLanguage.code) nextSourceDates[candidate.key] = now
    const configRows = page.sections.flatMap((section) => {
      const current = config[section.name]
      return [['enabled', String(current.enabled)], ['order', current.order], ['align', current.align], ['title_size', current.titleSize]].map(([name, value]) => ({ key: contentKey(page.slug, section.name, name), language: 'global', value, type: 'config', updated_by: user.id, updated_at: now }))
    })
    const configResult = await supabase.from('site_content').upsert(configRows, { onConflict: 'key,language' })
    if (configResult.error) return stop(`Error guardando la configuración global: ${configResult.error.message}`)

    const contentRows = saveCandidates.map((candidate) => ({
      key: candidate.key,
      language: candidate.language,
      value: candidate.value,
      type: candidate.type,
      updated_by: user.id,
      updated_at: now,
    }))
    if (contentRows.length) {
      const contentResult = await supabase.from('site_content').upsert(contentRows, { onConflict: 'key,language' })
      if (contentResult.error) return stop(`Error guardando el contenido traducible: ${contentResult.error.message}`)
    }
    if (saveCandidates.length) {
      const verificationResult = await supabase
        .from('site_content')
        .select('key, language, value')
        .in('key', [...new Set(saveCandidates.map((item) => item.key))])
        .in('language', [...new Set(saveCandidates.map((item) => item.language))])
      if (verificationResult.error) return stop(verificationResult.error.message)
      const persisted = new Map((verificationResult.data ?? []).map((row) => [contentIdentity(row.key, row.language), row.value]))
      const missing = saveCandidates.find((item) => persisted.get(contentIdentity(item.key, item.language)) !== item.value)
      if (missing) return stop(`No se pudo verificar el contenido guardado para ${missing.key} (${missing.language}).`)
    }
    const metadataEntries = saveCandidates.filter((candidate) => candidate.language !== baseLanguage.code).map((candidate) => {
      const identity = contentIdentity(candidate.key, candidate.language)
      const generated = autoGenerated.has(identity)
      const meta: TranslationMeta = { key: candidate.key, language: candidate.language, source_updated_at: nextSourceDates[candidate.key] ?? sourceUpdatedAt[candidate.key] ?? null, translated_at: now, translation_method: generated ? 'auto_generated' : 'manual', manually_edited: !generated }
      nextMetadata[identity] = meta
      return { ...meta, source_language: baseLanguage.code, updated_at: now }
    })
    if (metadataEntries.length) {
      const metadataResult = await supabase.from('content_translation_meta').upsert(metadataEntries, { onConflict: 'key,language' })
      if (metadataResult.error) return stop(`El contenido se guardó y verificó, pero falló la metadata de traducción: ${metadataResult.error.message}`)
    }
    const savedIdentities = new Set(saveCandidates.map((candidate) => contentIdentity(candidate.key, candidate.language)))
    setSourceUpdatedAt(nextSourceDates); setMetadata(nextMetadata); setAutoGenerated((current) => { const next = new Set(current); for (const identity of savedIdentities) next.delete(identity); return next }); setDirtyFields((current) => { const next = new Set(current); for (const identity of savedIdentities) next.delete(identity); return next }); setMessage('Contenido, configuración global y estado de traducciones guardados y verificados.'); setSaving(false)
    function stop(reason: string) { setError(reason); setSaving(false) }
  }

  async function translateGroups(groups: string[][], forceOverwrite = overwriteTranslations) {
    if (selectedLanguage === baseLanguage.code) { setError('Selecciona un idioma de destino.'); return }
    if (!providerStatus.available) { setError(providerStatus.message); return }
    setTranslating(true); setError(''); setMessage('')
    let nextValues = structuredClone(values), nextDirtyFields = new Set(dirtyFields), nextAutoGenerated = new Set(autoGenerated)
    for (const keys of groups) {
      const items = keys.flatMap((key) => {
        const sourceText = nextValues[key]?.[baseLanguage.code]?.trim() ?? ''
        const targetText = nextValues[key]?.[selectedLanguage]?.trim() ?? ''
        if (!sourceText || (targetText && !forceOverwrite)) return []
        return [{ key, value: sourceText, context: translationContext(page, key) }]
      })
      if (!items.length) continue
      const response = await fetch('/api/admin/translations', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ sourceLanguage: baseLanguage.code, targetLanguage: selectedLanguage, items }),
      })
      const result = await response.json() as { success?: boolean; translations?: Array<{ key: string; translatedValue: string }>; error?: string }
      if (!response.ok || !result.translations) {
        setError(result.error ?? 'No se pudo traducir el contenido.'); setTranslating(false); return
      }
      const batch = applyTranslationBatch(nextValues, nextDirtyFields, nextAutoGenerated, result.translations, selectedLanguage)
      nextValues = batch.nextValues
      nextDirtyFields = batch.nextDirtyFields
      nextAutoGenerated = batch.nextAutoGenerated
    }
    setValues(nextValues); setAutoGenerated(nextAutoGenerated); setDirtyFields(nextDirtyFields); setMessage('Traducción generada. Revísala antes de guardar.'); setTranslating(false)
  }

  function translatePage() {
    if (overwriteTranslations && !window.confirm(`Se reemplazarán las traducciones existentes en ${selected.native_name}. ¿Deseas continuar?`)) return
    const groups = page.sections.map((section) => section.translatableFields.map((field) => contentKey(page.slug, section.name, field.name)))
    void translateGroups(groups)
  }

  if (loading) return <p className="rounded-xl bg-white p-6 text-slate-500 shadow">Cargando contenido…</p>
  if (!baseLanguage || !selected) return <p className="rounded-xl bg-red-50 p-6 text-red-700">No hay un idioma base disponible.</p>

  return <form onSubmit={submit} className="space-y-6">
    <section className="rounded-xl bg-white p-6 shadow"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><p className="text-sm text-slate-500">{page.label} — {selected.native_name}</p><h2 className="mt-1 text-2xl font-bold">{selected.native_name}{selected.is_default && <span className="ml-2 text-sm font-normal text-slate-500">Idioma base</span>}</h2><p className="mt-2 text-sm text-slate-500">Traducción: {progress.percentage}% · {progress.pending} campos pendientes</p></div><div className="flex flex-wrap gap-3"><label className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={overwriteTranslations} onChange={(event) => setOverwriteTranslations(event.target.checked)} /> Sobrescribir traducciones existentes</label><button type="button" onClick={translatePage} disabled={translating || selected.is_default || !providerStatus.available} className="inline-flex items-center gap-2 rounded-lg border px-4 py-3 text-sm disabled:opacity-40"><Languages className="size-4" /> {translating ? 'Traduciendo...' : `Traducir página desde ${baseLanguage.native_name}`}</button><Link href="/admin/content/languages" className="rounded-lg bg-black px-4 py-3 text-sm font-medium text-white">+ Agregar idioma</Link></div></div><div className={`mt-4 rounded-lg border p-3 text-sm ${providerStatus.available ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-slate-200 bg-slate-50 text-slate-600'}`}><span className="mr-2" aria-hidden>{providerStatus.available ? '🟢' : '⚪'}</span>{providerStatus.message}</div><div className="mt-5 flex flex-wrap gap-2">{languages.map((language) => { const languageProgress = translationProgress(allFieldKeys, values, language.code, baseLanguage.code); return <button key={language.code} type="button" onClick={() => setSelectedLanguage(language.code)} className={`rounded-lg border px-4 py-2 text-sm font-semibold ${selectedLanguage === language.code ? 'border-black bg-black text-white' : 'bg-white'}`}>{language.code.toUpperCase()} · {language.is_default ? 'Base' : `${languageProgress.percentage}%`}</button> })}</div></section>

    {orderedSections.map((section, index) => { const sectionConfig = config[section.name] ?? initialSectionConfig(section, page.sections.indexOf(section)), key = (field: string) => contentKey(page.slug, section.name, field), sectionKeys = section.translatableFields.map((field) => key(field.name)); return <section key={section.name} className={`overflow-hidden rounded-xl bg-white shadow ${sectionConfig.enabled ? '' : 'opacity-70'}`}>
      <div className="flex flex-col justify-between gap-4 border-b p-6 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">#{sectionConfig.order}</span><h2 className="text-xl font-semibold">{section.label}</h2>{!sectionConfig.enabled && <span className="rounded-full bg-red-100 px-2.5 py-1 text-xs text-red-700">Inactiva</span>}</div><p className="mt-1 text-sm text-slate-500">{section.description}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void translateGroups([sectionKeys])} disabled={translating || selected.is_default || !providerStatus.available} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm disabled:opacity-40"><Languages className="size-4" /> {translating ? 'Traduciendo...' : 'Traducir sección'}</button><button type="button" disabled={index === 0} onClick={() => moveSection(section.name, -1)} className="rounded-lg border p-2 disabled:opacity-30" aria-label="Subir sección"><ArrowUp className="size-4" /></button><button type="button" disabled={index === orderedSections.length - 1} onClick={() => moveSection(section.name, 1)} className="rounded-lg border p-2 disabled:opacity-30" aria-label="Bajar sección"><ArrowDown className="size-4" /></button></div></div>
      <div className="grid gap-8 p-6 xl:grid-cols-[.75fr_1.25fr]"><div><p className="mb-3 text-xs font-semibold uppercase text-slate-400">Vista previa · {selected.code.toUpperCase()}</p><div className={`rounded-xl bg-slate-950 p-7 text-white ${sectionConfig.align === 'center' ? 'text-center' : sectionConfig.align === 'right' ? 'text-right' : 'text-left'}`}><p className="text-xs uppercase tracking-[.18em] text-cyan-300">{values[key('badge')]?.[selected.code] || section.label}</p><h3 className={`mt-4 font-bold ${sectionConfig.titleSize === 'small' ? 'text-2xl' : sectionConfig.titleSize === 'xlarge' ? 'text-4xl' : 'text-3xl'}`}>{values[key('title')]?.[selected.code] || section.label}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{values[key('subtitle')]?.[selected.code] || section.description}</p></div></div>
        <div className="space-y-5"><div><p className="mb-3 text-xs font-semibold uppercase text-slate-400">Configuración global de la sección</p><div className="grid gap-4 sm:grid-cols-4"><label className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={sectionConfig.enabled} onChange={(event) => setConfig((current) => ({ ...current, [section.name]: { ...current[section.name], enabled: event.target.checked } }))} /> Activa</label><label className="text-sm">Orden<input readOnly value={sectionConfig.order} className="mt-1 w-full rounded-lg border bg-slate-50 p-2.5" /></label><label className="text-sm">Alineación<select value={sectionConfig.align} onChange={(event) => setConfig((current) => ({ ...current, [section.name]: { ...current[section.name], align: event.target.value } }))} className="mt-1 w-full rounded-lg border p-2.5"><option value="left">Izquierda</option><option value="center">Centro</option><option value="right">Derecha</option></select></label><label className="text-sm">Título<select value={sectionConfig.titleSize} onChange={(event) => setConfig((current) => ({ ...current, [section.name]: { ...current[section.name], titleSize: event.target.value } }))} className="mt-1 w-full rounded-lg border p-2.5"><option value="small">Pequeño</option><option value="large">Grande</option><option value="xlarge">Extra grande</option></select></label></div></div>
          {section.translatableFields.map((field) => { const fieldKey = key(field.name), stale = isTranslationStale(metadata[`${fieldKey}:${selected.code}`], sourceUpdatedAt[fieldKey]); return <label key={field.name} className="block"><span className="mb-2 flex flex-wrap items-center justify-between gap-2 text-sm font-medium"><span>{field.label}{!values[fieldKey]?.[selected.code]?.trim() && !selected.is_default && <span className="ml-2 font-normal text-amber-600">Pendiente</span>}{stale && <span className="ml-2 font-normal text-orange-600">Traducción posiblemente desactualizada</span>}</span>{stale && <button type="button" onClick={() => void translateGroups([[fieldKey]], true)} className="inline-flex items-center gap-1 text-xs text-orange-700"><RefreshCw className="size-3" /> Regenerar desde {baseLanguage.native_name}</button>}</span>{field.type === 'textarea' ? <textarea value={values[fieldKey]?.[selected.code] ?? ''} onChange={(event) => updateValue(fieldKey, selected.code, event.target.value)} className="min-h-24 w-full rounded-lg border p-3" /> : <input value={values[fieldKey]?.[selected.code] ?? ''} onChange={(event) => updateValue(fieldKey, selected.code, event.target.value)} className="w-full rounded-lg border p-3" />}</label> })}
        </div></div>
    </section> })}
    {error && <p className="rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</p>}{message && <p className="rounded-lg bg-green-50 p-4 text-sm text-green-700">{message}</p>}
    <div className="sticky bottom-4 flex justify-end gap-3 rounded-xl border bg-white/95 p-4 shadow-lg backdrop-blur"><Link href="/admin/content" className="rounded-lg border px-5 py-3">Volver</Link><button disabled={saving || translating} className="rounded-lg bg-black px-6 py-3 font-medium text-white disabled:opacity-50">{saving ? 'Guardando…' : 'Guardar página'}</button></div>
  </form>
}

function contentKey(page: string, section: string, field: string) { return `${page}.${section}.${field}` }
function translationContext(page: ContentPageSchema, key: string) { const [, sectionName, fieldName] = key.split('.'); const section = page.sections.find((item) => item.name === sectionName); const field = section?.translatableFields.find((item) => item.name === fieldName); return `${page.label}; sección ${section?.label ?? sectionName}; campo ${field?.label ?? fieldName}.` }
function createInitialConfig(page: ContentPageSchema): Config { return Object.fromEntries(page.sections.map((section, index) => [section.name, initialSectionConfig(section, index)])) }
function initialSectionConfig(section: ContentPageSchema['sections'][number], index: number) { return { enabled: section.globalConfig.enabled, order: String(index + 1), align: section.globalConfig.align, titleSize: section.globalConfig.titleSize } }
function applyConfig(config: Config[string], field: string, value: string) { if (field === 'enabled') config.enabled = value !== 'false'; else if (field === 'order') config.order = value; else if (field === 'align') config.align = value; else if (field === 'title_size') config.titleSize = value }
function translationProgress(keys: string[], values: Values, language: string, baseLanguage?: string) { const applicable = baseLanguage ? keys.filter((key) => values[key]?.[baseLanguage]?.trim()) : keys; const translated = applicable.filter((key) => values[key]?.[language]?.trim()).length; return { total: applicable.length, translated, pending: applicable.length - translated, percentage: applicable.length ? Math.round((translated / applicable.length) * 100) : 100 } }
function isTranslationStale(meta: TranslationMeta | undefined, sourceDate: string | undefined) { return Boolean(meta?.source_updated_at && sourceDate && new Date(meta.source_updated_at).getTime() < new Date(sourceDate).getTime()) }
